# -*- coding:utf-8 -*-


#
# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.
#


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        
        """
        c = collections.Counter  # has the operation "minus"
        return list((c(t) - c(s)).elements())[0]
        """
        
        # use xor ^ faster
        m = 0
        for x in s+t:
            m ^= ord(x)  # need to change str into number
        return chr(m)
